### PR TITLE
Made iOS app navbar match web app navbar

### LINKED ISSUE #13: Fix order of navbar items (and add new sensors and remove stale sensors)
The navigation bar on the current version of the app is very outdated compared to the current web app. Modify the iOS navigation bar item order to match the order on the web application.

Another issue is that the default page that the app opens to is to a location we no longer have a sensor in - the location still works because it pulls from a URL for a sensor that is still active, but we should modify the title to match the current first index and log another bug (see Issue #15) about automating that.

### PR DESCRIPTION
**Pull request by anushadatar**
I updated the navigation bar in the view controller to match the navigation bar on the web app. If we want to have a larger conversation about the order of the navigation bar elements, we can, but I'd argue that should happen in aq-web-client (and then we'd want to update here) and that it might not be the highest priority at the moment. 

I haven't tested all the links on the simulator yet, but will when I build this.

### CODE REVIEW

**Comment by anushadatar** [comment]
Will squash on merge

**Comment by Inkering** [comment]
Looks good! If you test the build once it's done, ready to go!

**Review by Inkering — APPROVED** [review]
Lgtm!

**Comment by anushadatar** [comment]
Pushed, tested. and uploaded.

In the process, I also resolved and logged #15.

**Pull request merged**
