### PR TITLE
embed roboto font inside app

### LINKED ISSUE #6: Requires roboto font in downloads folder during build time

### PR DESCRIPTION
**Pull request by Inkering**
Instead of linking the roboto font to the downloads folder of whatever Mac is running Xcode, let's explicitly link it to a instance inside the app.

### CODE REVIEW

**Comment by Inkering** [comment]
@anushadatar When you get a chance, can you check if this builds and simulates correctly when you pull it down?

**Comment by anushadatar** [comment]
I don't have time until late tonight at the earliest to get that laptop set up and test this, but I will do this and post an update here!

**Comment by Inkering** [comment]
<3 no rush!

**Comment by anushadatar** [comment]
I tested this by removing robot from my downloads folder and deleting and re-pulling the repo (in case of caching things) on the air partners macbook. I was able to build and deploy on the simulator despite not having the font stored locally on my machine, so I am going to go ahead and merge this request. Great work Dieter!

**Review by anushadatar — APPROVED** [review]
LGTM, see PR comment for test procedure

**Pull request merged**
